#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
#   On the 9th iteration, displays "Hi" before "Best School".

read=0

while [ $read -lt 10 ]
do
  if [ $read -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( read++ ))
done
