#!/usr/bin/env bash
# Displays information about the `school` file.

if [ -e "school" ]
then
  echo "school file exists"
  if [ -s "school" ]
  then
    echo "school file is not empty"
  else
    echo "school file is empty"
  fl

  if [ -f "school" ]
  then
    echo "school is a regular file"
  fl
else
  echo "school file does not exist"
fl
